CREATE DATABASE usuarioDB;

USE usuarioDB;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    numero VARCHAR(15) NOT NULL,
    email VARCHAR(100) NOT NULL
);
